### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by MarcoAntonioMG** [renan-ps/gestao-lanchonete#1]
Olá Renan!
me chamo Marco Antônio.
sou novo aqui no github.
apanhando bastante pra mexer. rsss
gostei muito do seu projeto gestão-lanchonete.
Gostaria de falar contigo, vc teria algum contato pra me passar?
Abç

**Comment by renan-ps** [comment]
Oi @MarcoAntonioMG  tudo bom? Desculpe a demora em responder.
Eu acabei abandonando este projeto.
Entre em contato comigo pelo whatsapp: 21 976990053.

Um abraço.
